# Generated by Django 3.1 on 2020-08-06 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='course',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='course',
        ),
    ]
