# Generated by Django 3.1 on 2020-08-06 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200806_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.courses'),
        ),
        migrations.AddField(
            model_name='contact',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.courses'),
        ),
    ]
